### ISSUE TITLE
python 2 cleanup

### ISSUE THREAD

**Issue by brondsem** [TurboGears/Ming#39]
I dropped py2 support in https://github.com/TurboGears/Ming/commit/6c7ed0a1665cda2532854443cc96d80a4f4dbd0a but only did a bit of cleanup.

We can remove `__future__` imports, various `six` usage, etc.  https://github.com/asottile/pyupgrade can help.

**Comment by pgajdos** [comment]
Also could you please consider to use unittest.mock instead of mock, as fallback at least.

**Comment by brondsem** [comment]
Done via #46 including using `unittest.mock`
