### ISSUE TITLE
Pymongo `find_and_modify` is deprecated

### ISSUE THREAD

**Issue by ringeringeraja** [TurboGears/Ming#42]
https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.find_and_modify

**Comment by brondsem** [comment]
Yea, and there are quite a few other deprecated functions too.  Like insert/save/update/remove that need to be ..._one or ..._many etc.

**Comment by ringeringeraja** [comment]
> Yea, and there are quite a few other deprecated functions too. Like insert/save/update/remove that need to be ..._one or ..._many etc.

Will this be fixed sometime?
