### ISSUE TITLE
support pymongo 4.x

### ISSUE THREAD

**Issue by brondsem** [TurboGears/Ming#48]
Pymongo 4.x has a lot of breaking changes.  See https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-4-0  and https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html 
Certainly Ming will be affected significantly by save/insert/update/remove/find_and_modify being replaced with `_one` and `_many` versions

Pymongo 3.x last release was 3.13 in Nov 2022 https://pypi.org/project/pymongo/#history and there is no 3.x branches on github so probably 3.x is done being supported

3.x does support mongodb 5.0 and python 3.10 so that'll last for a while.

**Comment by mcepl** [comment]
I mean pymongo 4.0 is from [Nov 29, 2021](https://pypi.org/project/pymongo/4.0/), so either this project is dead or nobody cares enough to fix it. Which is it?

**Comment by brondsem** [comment]
Hi,

This project isn't dead, but its not very active either.  Supporting pymongo 4.x will take a lot of work, and pymongo 3.x still works well.  So it hasn't been addressed yet.

I am not familiar with any openSUSE package for Ming.  If it cannot use pymongo 3 there, then it seems like maybe it should be removed from openSUSE.  I don't know enough about that situation to suggest anything confidently though.

When Ming is installed via `pip`, then the `setup.py` constraints come into play and require `pymongo>=3.0,<4`.  So that installation method prevents version mismatch problems.

**Comment by mcepl** [comment]
Thank you for your honesty.

**Comment by brondsem** [comment]
Fixed via #60
